version: 2.1

defaults: &dockerImage
  docker:
    - image: circleci/node:13.8.0


jobs:
  build:
    <<: *dockerImage
    steps:
      - checkout
      - run: npm lint

  test:
    <<: *dockerImage
    steps:
      - checkout
      - run: npm i
      - run: npm run test

  analyze:
    <<: *dockerImage
    steps:
      - checkout
      - run: npm i
      - run: npm run audit


workflows:
  projpipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test





